name: build

on:
  push:
    paths:
      - 'release-versions/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Prepare Tags
        id: prepare_tags
        run: |
            DOCKER_IMAGE=rpdesouza/alltube
            ALLTUBE_VERSION=`cat release-versions/alltube-latest-release.txt`
            TAGS="--tag ${DOCKER_IMAGE}:latest"
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:${ALLTUBE_VERSION}"
            echo ::set-output name=buildx_tags::${TAGS}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.1.0
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
            docker buildx build --push \
            ${{ steps.prepare_tags.outputs.buildx_tags }} \
            --platform linux/amd64,linux/arm,linux/arm64/v8 . 
