name: build

on:
  push:
    paths:
      - 'release-versions/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
            DOCKER_IMAGE=rpdesouza/alltube
            DOCKER_PLATFORMS=linux/amd64,linux/arm,linux/arm64/v8
            ALLTUBE_VERSION=`cat release-versions/alltube-latest-release.txt`
            TAGS="--tag ${DOCKER_IMAGE}:latest"
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:${ALLTUBE_VERSION}"
            echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            ${TAGS} --file ./Dockerfile
      
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
            docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}
